// import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/src/footer/footer";
import FoundersButton from "@/src/button/FoundersButton";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  let textArray = [
    "Find us on:",
    "© Fireplace Palace",
    "Facebook Instagram Tiktok",
    "info@firepalace.co.uk",
  ];
  let footerItems = textArray.map((text) =>
    text.includes("@") ? (
      <a key={text} href="">
        {text}
      </a>
    ) : (
      <p key={text}>{text}</p>
    )
  );
  return (
    <html lang="en">
      <body className="container">
        <header className="logo">
          <p>🔥 Fireplace Palace</p>
        </header>
        <FoundersButton />
        <main>{children}</main>
        <Footer footerItems={footerItems} />
      </body>
    </html>
  );
}
